version: "3.8"

services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mysql
      - PMA_USER=laravel
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=1
    ports:
      - 8081:80
